sensors:
  #
  # Cameras convering both 2 bins and an agv
  #

  # depth_camera_test:
  #   type: depth_camera
  #   pose:
  #     xyz: [-7.5, 2.5, 1.801095]
  #     rpy: ['pi/2', 0, 'pi/2']

  logical_camera_bin_agv1:
    type: logical_camera
    pose:
      xyz: [-2.25, 4.00, 1.80]
      rpy: [0, 'pi/2', 0]

  logical_camera_bin_agv2:
    type: logical_camera
    pose:
      xyz: [-2.25, 2.00, 1.80]
      rpy: [0, 'pi/2', 0]

  logical_camera_bin_agv3:
    type: logical_camera
    pose:
      xyz: [-2.25, -2.00, 1.80]
      rpy: [0, 'pi/2', 0]

  logical_camera_bin_agv4:
    type: logical_camera
    pose:
      xyz: [-2.25, -4.00, 1.80]
      rpy: [0, 'pi/2', 0]

  #
  # Cameras for briefcases
  #

  logical_camera_as1:
    type: logical_camera
    pose:
      xyz: [-7.50, 3.00, 2.25]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_as2:
    type: logical_camera
    pose:
      xyz: [-12.50, 3.00, 2.25]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_as3:
    type: logical_camera
    pose:
      xyz: [-7.50, -3.00, 2.25]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_as4:
    type: logical_camera
    pose:
      xyz: [-12.50, -3.00, 2.25]
      rpy: [0, 'pi/2', 'pi/2']

  #
  # Cameras for agvs at assembly stations
  #

  logical_camera_agv1_as1:
    type: logical_camera
    pose:
      xyz: [-5.5, 4.5, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv1_as2:
    type: logical_camera
    pose:
      xyz: [-10.5, 4.5, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv2_as1:
    type: logical_camera
    pose:
      xyz: [-5.5, 1.4, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv2_as2:
    type: logical_camera
    pose:
      xyz: [-10.5, 1.4, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv3_as3:
    type: logical_camera
    pose:
      xyz: [-5.5, -1.4, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv3_as4:
    type: logical_camera
    pose:
      xyz: [-10.5, -1.4, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv4_as3:
    type: logical_camera
    pose:
      xyz: [-5.5, -4.5, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_agv4_as4:
    type: logical_camera
    pose:
      xyz: [-10.5, -4.5, 1.7]
      rpy: [0, 'pi/2', 'pi/2']

  #
  # Camera for the table where the trays come from
  #

  logical_camera_bin_trays:
    type: logical_camera
    pose:
      xyz: [-6.092189, 6.166299, 2.051140]
      rpy: [3.141593, 1.570792, 0.000000]

  #
  # Breakbeam for detecting humans
  #

  # assembly station 2

  breakbeam_as2_table:
    type: break_beam
    pose:
      xyz: [-11.45, 3.55, 0.20]
      rpy: [0, 0, -1.57]

  breakbeam_as2_pen:
    type: break_beam
    pose:
      xyz: [-8.77, 3.55, 0.20]
      rpy: [0, 0, -1.57]

  # assembly station 3

  breakbeam_as4_table:
    type: break_beam
    pose:
      xyz: [-11.45, -3.55, 0.20]
      rpy: [0, 0, 1.57]

  breakbeam_as4_pen:
    type: break_beam
    pose:
      xyz: [-8.77, -3.55, 0.20]
      rpy: [0, 0, 1.57]

#
# Robot-mounted cameras
#

gantry_bin_camera:
  enable: false

gantry_tray_camera:
  enable: false
