# ARIAC 2022
# This trial file uses multiple things at once:
# 10 blue pumps spawn on the conveyor belt
# The briefcase at as1 is partially filled.
# submitting the kitting shipment in order_0 will announce order_1 (regular order)

options:
  insert_models_over_bins: true
  belt_population_cycles: 10
  insert_models_over_stations: true
  gazebo_state_logging: false
  # mandatory: gripper_tray or gripper_part
  current_gripper_type: gripper_tray
time_limit: -1


# The table_tray_infos is not mandatory
# The different options for tray_model are:
#  -movable_tray_metal_shiny
#  -movable_tray_metal_rusty
#  -movable_tray_dark_wood
#  -movable_tray_light_wood
# quantity can be: 1, 2, or 3
table_tray_infos:
  table_2: 
    tray_model: movable_tray_dark_wood
    quantity: 1

# mandatory: location of agvs and products at start
agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4

# Only one order 
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1 
    # disable_robot: [kitting_robot, agv1, 1] # [kitting_robot, agv1, 1]
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      trays: [movable_tray_dark_wood]
      agvs: [agv1]
      destinations: [as1]
      products:
        part_0:
          type: assembly_pump_blue
          pose:
            xyz: [-0.1, -0.1, 0.0]
            rpy: [0.0, 0.0, 0.0]
  order_1:
    priority: 1 # default is 1 if omitted, we could omit this line
    kitting_robot_health: 1 
    assembly_robot_health: 1
    announcement_condition: kitting_submission
    announcement_condition_value: [agv1, as1]
    assembly:
      shipment_count: 1
      stations: [as1]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [0.032, -0.153, 0.076]
            rpy: [0, 0, 0]

models_over_stations:
  as1:
    models:
      assembly_battery_blue:
        xyz: [-0.032465, 0.174845, 0.15]
        rpy: [0, 0, 0]

belt_models:
  assembly_pump_blue:
    5.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']



# don't forget to include at least 1 empty line here

