# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gantry_full
  joint_model_group_pose: gantry_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - small_long_joint
    - torso_rail_joint
    - torso_base_main_joint
    - gantry_arm_shoulder_pan_joint
    - gantry_arm_shoulder_lift_joint
    - gantry_arm_elbow_joint
    - gantry_arm_wrist_1_joint
    - gantry_arm_wrist_2_joint
    - gantry_arm_wrist_3_joint
    - gantry_arm_vacuum_gripper_joint
    - torso_main_torso_tray_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /ariac/gantry/gantry_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gantry_arm_shoulder_pan_joint
      - gantry_arm_shoulder_lift_joint
      - gantry_arm_elbow_joint
      - gantry_arm_wrist_1_joint
      - gantry_arm_wrist_2_joint
      - gantry_arm_wrist_3_joint
    constraints:
      goal_time: 3
    stop_trajectory_duration: 3
    gains:
      gantry_arm_shoulder_pan_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
      gantry_arm_shoulder_lift_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 50
      gantry_arm_elbow_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 25
      gantry_arm_wrist_1_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
      gantry_arm_wrist_2_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
      gantry_arm_wrist_3_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
  - name: /ariac/gantry/gantry_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint
    constraints:
      goal_time: 5
      gantry_arm_elbow_joint:
        goal: 0.5
        trajectory: 0.5
    stop_trajectory_duration: 3
    gains:
      small_long_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
      torso_rail_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
      torso_base_main_joint:
        p: 10000
        d: 0
        i: 10
        i_clamp: 1
