# ARIAC 2022
# Trial for the faulty part challenge.
# 2 parts are faulty in bin2

options:
  insert_models_over_bins: false
  belt_population_cycles: 0
  insert_models_over_stations: false
  gazebo_state_logging: true
  # mandatory: gripper_tray or gripper_part
  current_gripper_type: gripper_tray
time_limit: -1


# mandatory: location of agvs and products at start
agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4

# Only one order 
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1 
    # disable_robot: [kitting_robot, agv1, 1] # [kitting_robot, agv1, 1]
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      trays: [movable_tray_metal_shiny]
      agvs: [agv1]
      destinations: [as1]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [-0.1, -0.1, 0.0]
            rpy: [0.0, 0.0, 0.0]


faulty_products:
  - assembly_pump_red_1
  - assembly_pump_red_2


# don't forget to include at least 1 empty line here

