# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

on: # this determines when this workflow is run
  push:
     branches: [ main, devel ] #  when master or melodic-devel branch is pushed to
  pull_request:
     branches: [ main, devel ] # when there is a pull request against master
  workflow_dispatch: # allow manually starting this workflow

jobs:
  industrial_ci:
    name: ROS Tests
    runs-on: ubuntu-runner-lima-1
    strategy:
      matrix: # matrix is the product of entries
        ROS_DISTRO: [melodic]
        ROS_REPO: [main]
    env:
      ADDITIONAL_DEBS: python-catkin-lint
      PARALLEL_BUILDS: 8
      PARALLEL_TESTS:  1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: 'ros-industrial/industrial_ci@master' # run industrial_ci
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
