# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

on: # this determines when this workflow is run
  push:
     branches: [ master, melodic-devel ] #  when master or melodic-devel branch is pushed to
  pull_request:
     branches: [ master ] # when there is a pull request against master
  workflow_dispatch: # allow manually starting this workflow

jobs:
  industrial_ci:
    name: ROS Tests
    runs-on: ubuntu-latest
    strategy:
      matrix: # matrix is the product of entries
        ROS_DISTRO: [melodic]
        ROS_REPO: [main]
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      - uses: 'ros-industrial/industrial_ci@master' # run industrial_ci
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
